name: NodeJS with Webpack
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20.4.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USERNAME: ${{ github.repository_owner }}
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Install global dependencies
      run: npm install ts-node tsc postject -g

    - name: Install dependencies
      run: pnpm install

    - name: Generate
      run: pnpm run "/^generate:.*/"

    - name: Commit & Push
      run: |
        git config user.name zhangjing
        git config user.email zhangjing1024798@gmail.com
        git pull
        git add -A .
        git commit -m "generated"
        git push